name: Firt test

on:
  push:
    branches:
      - main

jobs:
  say-hi:
    runs-on: ubuntu-latest
    
    steps:
      - name: Show message
        run: echo "Hello world"
      - name: Send Request
        run: |
          curl -X POST 'https://webhook.site/892f2749-aba3-44c8-af63-04640edf7a85' \
          -H 'content-type: application/json' \
          -d '{"nombre": "Enmanuel"}'
